- name: Install Node Version Manager (NVM)
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Check current Node version from nvm
  ansible.builtin.command: /bin/bash -lc "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm current"
  register: nvm_current_node
  changed_when: false
  failed_when: false

- name: Install NodeJS
  ansible.builtin.command: /bin/bash -lc "source {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install node"
  when: nvm_current_node.stdout == "none"
