- name: installing NeoVim
  community.general.homebrew:
    name: neovim
    state: latest

- name: setting up AstroNvim
  ansible.builtin.git:
    repo: https://github.com/AstroNvim/template
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    depth: 1

- name: remove AstroNvim git metadata
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim/.git"
    state: absent
